build(upsidle): configure husky to install on postinstall (#9)
* build(upsidle): configure husky to install on postinstall

* ci(upsidle): restrict commit directly to develop or master branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Get the current branch
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+# Ensure that no commit is made directly to the main or develop branch
+if [ "$branch" = "develop" ] || [ "$branch" = "main" ]; then
+  echo "You can't commit directly to $branch branch"
+  exit 1
+fi
+
 yarn lint-staged
